spring:
  application:
    name: user-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:/app/data/userdb;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6380}
  cache:
    redis:
        time-to-live: 60000
  threads:
    virtual:
      enabled: true
spring.h2.console.enabled: true

server:
  port: 8080

logging:
  level:
    dre.userservice: DEBUG
    dre.userservice.service.impl: DEBUG
    org.springframework.web: DEBUG
